from src.constructionMoves.removeLonelyGenderMove import RemoveLonelyGenderMove
from src.constructionMoves.swapLonelyGenderMove import SwapLonelyGenderMove
from src.constructionMoves.getSameGenderMove import GetSameGenderMove
from src.constructionMoves.findHostWithSwaps import FindHostWithSwapsMove